name: Build greenpizza

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}

      - uses: actions/checkout@v4

      - name: Use shared variable
        run: |
          JFROG_CLI_BUILD_NAME=${{ vars.BUILD_NAME }}
          JFROG_CLI_BUILD_NUMBER=${{ github.run_number }}

      - name: Collect commits into buildinfo
        run: jfrog rt build-add-git ${{ vars.BUILD_NAME }} ${{ github.run_number }}

      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          install: true

      - name: Build Docker image
        run: |
          URL=$(echo ${{ vars.ARTIFACTORY_URL }} | sed 's|^https://||')
          REPO_URL=${URL}'/${{ vars.PROJECT }}-docker-dev-virtual'
          docker build --build-arg REPO_URL=${REPO_URL} -f go-server/Dockerfile . \
          --tag ${REPO_URL}/${{ vars.PROJECT }}-app:${{ github.run_number }} \
          --output=type=image --platform linux/amd64 --metadata-file=build-metadata --push
          jfrog rt build-docker-create ${{ vars.PROJECT }}-docker-dev --image-file build-metadata --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}


      - name: Upload readme file
        run: |
          jf rt upload ./README.md ${{ vars.PROJECT }}-generic-dev/readme/${{ github.run_number }}/ --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}

      - name: Publish build info
        run: jfrog rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }}



