name: Build-and-Create-Evidence

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Collect commits into buildinfo
        run: jfrog rt build-add-git 

      - name: Collecting Environment Variables into buildinfo
        run: jfrog rt build-collect-env 

      - name: Upload readme file
        run: |
          jf rt upload ./README.md ${{ vars.PROJECT }}-generic-dev/readme/attest/ 

      - name: Publish build info
        run: jfrog rt build-publish 

      - uses: actions/attest-build-provenance@v1
        with:
          # subject-path: ${{ vars.PROJECT }}-generic-dev/readme/attest/README.md
          subject-digest: sha256:${{ hashFiles('README.md') }}
          subject-name: README.md

#      - uses: jfrog/evidence-build-provenance@v0.1
      - uses: neshkoli/build-provenance@v1
        with:
          artifact-path: README.md

      - name: print provenance
        run: |
          echo "provenance.json is:"
          cat provenance.json

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

