name: Build-and-Attest

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Use shared variable
        run: |
          JFROG_CLI_BUILD_NAME=${{ vars.BUILD_NAME }}
          JFROG_CLI_BUILD_NUMBER=${{ github.run_number }}

      - name: Collect commits into buildinfo
        run: jfrog rt build-add-git ${{ vars.BUILD_NAME }} ${{ github.run_number }}

      - name: Collecting Environment Variables into buildinfo
        run: jfrog rt build-collect-env ${{ vars.BUILD_NAME }} ${{ github.run_number }}

      # - name: Log in to Artifactory Docker Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.ARTIFACTORY_URL }}
      #     username: ${{ secrets.JF_USER }}
      #     password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     install: true

      # - name: Build Docker image
      #   run: |
      #     URL=$(echo ${{ vars.ARTIFACTORY_URL }} | sed 's|^https://||')
      #     REPO_URL=${URL}'/${{ vars.PROJECT }}-docker-dev-virtual'
      #     docker build --build-arg REPO_URL=${REPO_URL} -f go-server/Dockerfile . \
      #     --tag ${REPO_URL}/${{ vars.PROJECT }}-app:${{ github.run_number }} \
      #     --output=type=image --platform linux/amd64 --metadata-file=build-metadata --push
      #     jfrog rt build-docker-create ${{ vars.PROJECT }}-docker-dev --image-file build-metadata --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}


      - name: Upload readme file
        run: |
          jf rt upload ./README.md ${{ vars.PROJECT }}-generic-dev/readme/attest/ --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}

      - name: Publish build info
        run: jfrog rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }}

      - uses: actions/attest-build-provenance@v1
        with:
          # subject-path: ${{ vars.PROJECT }}-generic-dev/readme/attest/README.md
          subject-digest: sha256:$(sha256sum ./README.md | awk '{print $1}')
          subject-name: README.md


