name: Build-and-Attest

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Collect commits into buildinfo
        run: jfrog rt build-add-git 

      - name: Collecting Environment Variables into buildinfo
        run: jfrog rt build-collect-env 

      - name: Upload readme file
        run: |
          jf rt upload ./README.md ${{ vars.PROJECT }}-generic-dev/readme/attest/ 

      - name: Publish build info
        run: jfrog rt build-publish 

      - uses: actions/attest-build-provenance@v1
        with:
          # subject-path: ${{ vars.PROJECT }}-generic-dev/readme/attest/README.md
          subject-digest: sha256:${{ hashFiles('README.md') }}
          subject-name: README.md

      - name: Build Provenance
        uses: neshkoli/build-provenance@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'provenance.json'
          # target-path: ${{ vars.PROJECT }}-generic-dev/readme/attest/
          
      # - name: Install dependencies for slsa-provenance
      #   run: |
      #     cd ./.github/actions/slsa-provenance
      #     npm install

      # - name: Generate SLSA Provenance
      #   uses: ./.github/actions/slsa-provenance
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     output-path: 'provenance.json'

      - name: print provenance
        run: |
          echo "provenance.json is:"
          cat provenance.json

      # - name: Collect Provenance Data
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # Collect basic information
      #     echo "Repository: ${{ github.server_url }}/${{ github.repository }}" >> provenance.txt
      #     echo "Commit: ${{ github.sha }}" >> provenance.txt
      #     echo "Ref: ${{ github.ref }}" >> provenance.txt
      #     echo "Runner OS: ${{ runner.os }}" >> provenance.txt
      #     echo "Runner Arch: ${{ runner.arch }}" >> provenance.txt
      #     echo "Workflow: ${{ github.workflow }}" >> provenance.txt
      #     echo "Run ID: ${{ github.run_id }}" >> provenance.txt
      #     echo "Run Number: ${{ github.run_number }}" >> provenance.txt

      #     # Fetch job and step information using GitHub API
      #     JOB_INFO=$(curl -H "Authorization: token $GITHUB_TOKEN" \
      #       "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")
      #     echo "$JOB_INFO" | jq '.jobs[] | {name, status, steps: [.steps[] | {name, status, conclusion}]}' >> provenance.txt

      #     echo "provenance.txt is:"
      #     cat provenance.txt



